# Generated by Django 6.0.3 on 2026-03-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant de la commission en FCFA', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Taux de commission en % prélevé par la plateforme', max_digits=5),
        ),
    ]
