# Generated by Django 6.0.3 on 2026-03-18 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_domaine_user_profile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('gratuit', 'Gratuit'), ('standard', 'Standard'), ('pro', 'Pro')], default='gratuit', max_length=20, verbose_name='Plan abonnement'),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration du plan'),
        ),
        migrations.CreateModel(
            name='SubscriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_demande', models.CharField(choices=[('gratuit', 'Gratuit'), ('standard', 'Standard'), ('pro', 'Pro')], max_length=20, verbose_name='Plan demandé')),
                ('moyen_paiement', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money')], max_length=20, verbose_name='Moyen de paiement')),
                ('numero_transaction', models.CharField(max_length=100, verbose_name='Numéro de transaction')),
                ('duree_mois', models.PositiveSmallIntegerField(default=1, verbose_name='Durée (mois)')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('traite_le', models.DateTimeField(blank=True, null=True)),
                ('note_admin', models.TextField(blank=True, verbose_name='Note admin')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'vendeur'}, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'abonnement",
                'verbose_name_plural': "Demandes d'abonnement",
                'ordering': ['-created_at'],
            },
        ),
    ]
